import test from 'node:test';import assert from 'node:assert/strict';
import {buyer,selection,whatsappMessage,whatsappNumber} from '../server/wholesale/policy.mjs';
import {createApp} from './helpers/business-app.mjs';
const person={nombre:' Prueba Local ',email:'FIXTURE@EXAMPLE.INVALID',whatsapp:'1100000000',localidad:'Tandil',provincia:' BUENOS AIRES ',empresa:'',comentarios:'No divulgar secret-marker'};
test('wholesale canonical buyer, province and selection strip browser prices/attribution',()=>{const b=buyer({...person,role:'admin'});assert.equal(b.provincia,'Buenos Aires');assert.equal(b.email,'fixture@example.invalid');assert.equal(b.role,undefined);assert.deepEqual(selection([{id:2,cantidad:10,precio:1,stock:999,ref:'forged'}]),[{id:'2',cantidad:10}]);});
test('wholesale rejects invalid contact, quantities, duplicate variants and unavailable contact',()=>{for(const data of [{...person,email:'not-email'},{...person,provincia:'Atlantis'},{...person,whatsapp:'abc'},{...person,comentarios:'x'.repeat(1001)}])assert.throws(()=>buyer(data));for(const data of [[],[{id:'2',cantidad:0}],[{id:'2',cantidad:1.2}],[{id:'2',cantidad:1001}],[{id:'2',cantidad:1},{id:2,cantidad:2}],[{id:'1e2',cantidad:10}]])assert.throws(()=>selection(data));assert.throws(()=>whatsappNumber(''));});
test('WhatsApp is prepared from persisted receipt and omits contact/comments/private identifiers',()=>{const message=whatsappMessage({number:'MAY-0001',buyer:person,id:'private-marker',quote:{total:80000,items:[{quantity:10,name:'Mate local'}]}});assert.match(message,/MAY-0001/);assert.match(message,/seña correspondiente/);assert.match(message,/10 × Mate/);for(const value of ['secret-marker','private-marker','EXAMPLE.INVALID','1100000000'])assert.ok(!message.includes(value));});
async function fixture(t,{ready=true,user=null}={}){const calls=[];const {app}=createApp({url:'http://127.0.0.1:54321',secret:'local-placeholder',publishable:'local-placeholder',origin:'https://matebreak.test',wholesaleWhatsapp:ready?'540000000000':'',production:false,shippingMode:'mock',paymentsMode:'mock'}, {admin:{rpc:async(name,args)=>{calls.push({name,args});if(name==='mb_wholesale_access')return{data:true};if(name==='mb_inventario_autorizado')return{data:false};if(name==='mb_wholesale_catalog')return{data:{minimum:10,referenceValid:!args.p_ref||args.p_ref==='seller01',items:[{id:'2',price:8000,eligibleUnits:1,imagePath:null}]}};if(name==='mb_wholesale_quote')return{data:{total:80000,eligible:true}};if(name==='mb_wholesale_submit_account')return{data:{number:'MAY-0001',state:'recibida',quote:{total:80000,items:[{name:'Mate local',quantity:10}]}}};return{error:{code:'42501',message:'Access denied'}};}},authFactory:()=>({auth:{getSession:async()=>({data:{session:{access_token:'local.'+Buffer.from(JSON.stringify({session_id:'aaaaaaaa-1111-4111-8111-111111111111'})).toString('base64url')+'.fixture'}}}),getUser:async()=>({data:{user}})}})});const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>new Promise(r=>server.close(r)));const base='http://127.0.0.1:'+server.address().port;const post=(path,body,cookie='',origin='https://matebreak.test')=>fetch(base+path,{method:'POST',headers:{origin,'content-type':'application/json',cookie},body:JSON.stringify(body)});return{base,calls,post};}
test('HTTP catalog fixes first touch, final submission forwards only trusted inputs and hashed owner',async t=>{const {base,calls,post}=await fixture(t,{user:{id:'11111111-1111-4111-8111-111111111111'}});const response=await fetch(base+'/api/mayorista/catalogo?ref=seller01');assert.equal(response.status,200);const cookies=response.headers.getSetCookie().map(v=>v.split(';')[0]).join('; ');assert.ok(!cookies.includes('__Host-mb_wholesale='));assert.match(cookies,/__Host-mb_wholesale_ref=seller01/);assert.match(response.headers.get('cache-control'),/no-store/);const result=await post('/api/mayorista/solicitudes',{idempotencia:'11111111-1111-4111-8111-111111111111',comprador:person,items:[{id:2,cantidad:10,precio:0}],ref:'evil'},cookies);assert.equal(result.status,201);assert.equal(calls.at(-1).args.p_ref,'seller01');assert.equal(calls.at(-1).args.p_user,'11111111-1111-4111-8111-111111111111');assert.equal(calls.at(-1).args.p_owner,undefined);assert.deepEqual(calls.at(-1).args.p_items,[{id:'2',cantidad:10}]);const receipt=await result.json();assert.equal(receipt.buyer,undefined);assert.match(receipt.whatsappUrl,/^https:\/\/wa.me\//);await fetch(base+'/api/mayorista/catalogo?ref=evil',{headers:{cookie:cookies}});assert.equal(calls.at(-1).args.p_ref,'seller01');});
test('HTTP unknown references, unavailable contact, anonymous management and cross origin are rejected',async t=>{const {base,post,calls}=await fixture(t,{ready:false,user:{id:'11111111-1111-4111-8111-111111111111'}});assert.equal((await fetch(base+'/api/mayorista/catalogo?ref=unknown')).status,400);assert.equal((await post('/api/mayorista/solicitudes',{})).status,503);assert.equal(calls.filter(c=>c.name==='mb_wholesale_submit').length,0);assert.equal((await fetch(base+'/api/admin/mayorista')).status,403);assert.equal((await post('/api/mayorista/cotizar',{items:[{id:2,cantidad:10}]},'', 'https://evil.test')).status,403);});
test('HTTP spam limiter protects leads separately from quotations',async t=>{const {post}=await fixture(t,{user:{id:'11111111-1111-4111-8111-111111111111'}});for(let i=0;i<6;i++)assert.equal((await post('/api/mayorista/solicitudes',{})).status,400);assert.equal((await post('/api/mayorista/solicitudes',{})).status,429);assert.equal((await post('/api/mayorista/cotizar',{items:[{id:2,cantidad:10}]})).status,200);});
test('authenticated user metadata cannot grant wholesale administration',async t=>{const {base,calls}=await fixture(t,{user:{id:'11111111-1111-4111-8111-111111111111',user_metadata:{rol:'administrador'}}});assert.equal((await fetch(base+'/api/admin/mayorista')).status,403);assert.equal(calls.filter(c=>c.name==='mb_wholesale_manage').length,0);});
