import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {startWholesalePreview} from '../scripts/wholesale-preview-runtime.mjs';
const {chromium}=await import(process.env.MATEBREAK_PLAYWRIGHT_MODULE||'playwright');
const evidence=path.resolve(process.env.MATEBREAK_EVIDENCE_DIR||''),root=path.resolve(import.meta.dirname,'..');
assert.ok(process.env.MATEBREAK_EVIDENCE_DIR&&evidence.toLowerCase()!==root.toLowerCase()&&!evidence.toLowerCase().startsWith(root.toLowerCase()+path.sep));fs.mkdirSync(evidence,{recursive:true});
const preview=await startWholesalePreview(),browser=await chromium.launch({channel:'chrome',headless:true}),report={source:'loopback Express + disposable PostgreSQL; synthetic data only',cases:[],errors:[],requests:[]};
try{
 for(const width of [1440,360]){
  const context=await browser.newContext({viewport:{width,height:900}}),page=await context.newPage();
  await page.addInitScript(()=>{window.open=(url)=>{window.__openedWholesale=url;return null;};Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>{window.__copiedWholesale=value;}}});});
  page.on('pageerror',e=>report.errors.push({width,message:e.message}));
  // External WhatsApp is never contacted. Permit only public fonts/Tailwind/images.
  await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===preview.base||['fonts.googleapis.com','fonts.gstatic.com','cdn.tailwindcss.com','lh3.googleusercontent.com'].includes(u.hostname))return r.continue();return r.abort();});
  page.on('request',r=>{const u=new URL(r.url());if(u.origin===preview.base&&u.pathname.startsWith('/api/'))report.requests.push({width,path:u.pathname,method:r.method()});});
  await page.goto(preview.base+'/');assert.equal(await page.locator('a[data-path=regalos]').textContent(),'Compra Mayorista');await page.locator('a[data-path=regalos]').click();await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:evidence+'/wholesale-entry-'+width+'.png',fullPage:true});
  if(width===360)await page.goto(preview.base+'/mayorista?ref=seller01');else await page.goto(preview.base+'/mayorista');await page.waitForFunction(()=>document.querySelectorAll('.wholesale-product').length===2);assert.equal(await page.locator('.wholesale-photo').first().innerText(),'Foto pendiente');assert.equal(await page.locator('#wholesale-continue').isEnabled(),false);await page.screenshot({path:evidence+'/wholesale-catalog-'+width+'.png',fullPage:true});
  const mate=page.locator('[data-variant="900001"]'),accessory=page.locator('[data-variant="900004"]');
  async function set(card,qty){await card.locator('input').fill(String(qty));await card.locator('button').click();await page.waitForFunction(()=>document.querySelector('#wholesale-total').textContent!=='—');}
  await set(mate,5);await set(accessory,5);assert.match(await page.locator('#wholesale-minimum').innerText(),/5 unidades elegibles/);assert.equal(await page.locator('#wholesale-continue').isEnabled(),false);
  await set(accessory,0);await set(mate,10);assert.match(await page.locator('#wholesale-total').innerText(),/80.000/);assert.equal(await page.locator('#wholesale-continue').isEnabled(),true);await page.locator('#wholesale-continue').click();
  for(const [name,value] of Object.entries({nombre:'Prueba Local '+width,empresa:'Empresa sintética',whatsapp:'1100000000',email:'fixture'+width+'@example.invalid',localidad:'Tandil',comentarios:'Logo ficticio local'}))await page.locator('[name='+name+']').fill(value);await page.locator('[name=provincia]').selectOption('Buenos Aires');assert.equal(await page.locator('[name=provincia] option').count(),25);await page.screenshot({path:evidence+'/wholesale-buyer-'+width+'.png',fullPage:true});
  // Simulate lost response after server committed: retry must replay the same saved key/payload.
  let attempts=0;await page.route('**/api/mayorista/solicitudes',async route=>{attempts++;if(attempts===1){await route.fetch();return route.abort('failed');}return route.continue();});
  await page.locator('#wholesale-submit').click();await page.waitForFunction(()=>document.querySelector('#wholesale-status').textContent.includes('reintentar'));assert.equal(await page.locator('[name=nombre]').isEnabled(),false);await page.locator('#wholesale-submit').click();await page.locator('#wholesale-receipt').waitFor();assert.match(await page.locator('#receipt-title').innerText(),/^MAY-/);assert.equal(await page.evaluate(()=>window.__openedWholesale?.startsWith('https://wa.me/')),true);assert.ok(!(await page.locator('#wholesale-message').inputValue()).includes('example.invalid'));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:evidence+'/wholesale-receipt-'+width+'.png',fullPage:true});await page.locator('#wholesale-copy').click();await page.waitForFunction(()=>document.querySelector('#wholesale-status').textContent.includes('Mensaje copiado'));assert.equal(await page.evaluate(()=>window.__copiedWholesale),await page.locator('#wholesale-message').inputValue());assert.equal(attempts,2);assert.equal(await page.locator('#wholesale-whatsapp').getAttribute('rel'),'noopener noreferrer');await context.close();report.cases.push({width,status:'PASS',catalog:2,minimum:'5 mates + 5 accessories fails; 10 mates passes',total:80000,replay:'one lost response + identical retry = one lead'});
 }
 assert.equal(preview.db.query("select origin from private.wholesale_request where buyer->>'nombre'='Prueba Local 1440';"),'web_sin_referencia');assert.equal(preview.db.query("select origin from private.wholesale_request where buyer->>'nombre'='Prueba Local 360';"),'enlace_vendedor');
 const adminContext=await browser.newContext({viewport:{width:1440,height:900},extraHTTPHeaders:{'x-local-preview-admin':'1'}}),adminPage=await adminContext.newPage();adminPage.on('pageerror',e=>report.errors.push({case:'admin',message:e.message}));await adminPage.goto(preview.base+'/healthz');await adminPage.setContent('<div id="message"></div><button id="wholesale-admin-refresh">Actualizar</button><div id="wholesale-admin-list"></div>');await adminPage.evaluate(async()=>{const {mountWholesaleAdmin}=await import('/src/features/account/account-wholesale.js');await mountWholesaleAdmin();});assert.equal(await adminPage.locator('.wholesale-admin-row').count(),2);const row=adminPage.locator('.wholesale-admin-row').first();await row.locator('[name=closer]').fill('44444444-4444-4444-8444-444444444444');await row.locator('button').click();await adminPage.waitForFunction(()=>document.querySelector('.wholesale-admin-row h3')?.textContent.includes('en conversacion'));await adminContext.close();report.cases.push({name:'admin manages local request',status:'PASS'});
 assert.equal(preview.db.query('select count(*) from private.wholesale_request;'),'2');assert.equal(preview.db.query('select count(*) from private.wholesale_event;'),'3');assert.equal(preview.db.query('select count(*) from public.pedido;'),'0');assert.equal(preview.db.query('select count(*) from public.pago;'),'0');assert.equal(preview.db.query('select string_agg(stock::text,\',\' order by id_producto) from public.producto_simple where id_producto in (900002,900003);'),'100,100');assert.equal(report.errors.length,0);report.database={leads:2,events:3,orders:0,payments:0,stock:'100/100'};
}finally{fs.writeFileSync(evidence+'/wholesale-browser-result.json',JSON.stringify(report,null,2)+'\n');await browser.close();await preview.close();}
console.log(JSON.stringify(report.cases));
