import test from 'node:test';import assert from 'node:assert/strict';
import {registration,completion,phone,persistRegistration} from '../server/wholesale/profile.mjs';
import {commercialContext} from '../server/wholesale/context.mjs';
const data={nombre:' Ana ',apellido:' Pérez ',whatsapp:'01112345678',provincia:'BUENOS AIRES',localidad:' Tandil ',empresa:' Empresa '};
test('wholesale registration validates all data, preserves phone zeros and ignores authorization input',()=>{assert.deepEqual(registration({...data,rol:'administrador',id:'forged'}),{nombre:'Ana Pérez',whatsapp:'01112345678',provincia:'Buenos Aires',localidad:'Tandil',empresa:'Empresa'});for(const k of ['nombre','apellido','whatsapp','provincia','localidad'])assert.throws(()=>registration({...data,[k]:''}));for(const phoneValue of [12345678,'1e10','123','1234567890123456','abc'])assert.throws(()=>phone(phoneValue));});
test('profile completion never accepts identity, email or roles and supports partial missing fields',()=>{assert.deepEqual(completion({localidad:'Tandil'}),{localidad:'Tandil'});for(const data of [{id:'x'},{email:'x'},{rol:'admin'},{},null])assert.throws(()=>completion(data));});
test('registration display metadata persists through authenticated RLS only; invalid metadata never grants permissions',async()=>{let calls=[];await persistRegistration({rpc:async(...args)=>{calls.push(args);return{};}},{user_metadata:{mayorista:{nombre:'Ana Pérez',whatsapp:'01112345678',provincia:'Buenos Aires',localidad:'Tandil'}}});assert.equal(calls.length,1);assert.equal(calls[0][0],'mb_wholesale_profile_complete');assert.equal(calls[0][1].p_user,undefined);await persistRegistration({rpc:()=>{throw Error('must not call');}},{user_metadata:{mayorista:{role:'admin'}}});});
test('saved commercial fields prefill request; existing AR addresses avoid needless completion',()=>{const result=commercialContext({id:'owner',email:'verified@example.invalid'},{nombre:'Ana Pérez',telefono:'01112345678',provincia:'Buenos Aires',localidad:'Tandil',empresa:'Fixture'},[]);assert.deepEqual(result.missing,[]);assert.equal(result.buyer.empresa,'Fixture');assert.equal(result.buyer.email,'verified@example.invalid');const old=commercialContext({id:'owner',email:'verified@example.invalid'},{nombre:'Ana Pérez',telefono:'01112345678'},[{pais:'AR',ciudad:'Tandil',departamento:'Buenos Aires'}]);assert.deepEqual(old.missing,[]);});

