import test from 'node:test';import assert from 'node:assert/strict';
import {createApp} from '../server/app.mjs';import {returnPath} from '../src/features/account/return-path.mjs';
const uid='11111111-1111-4111-8111-111111111111',sid='aaaaaaaa-1111-4111-8111-111111111111';
test('return destinations reject external, encoded, inherited and arbitrary paths',()=>{assert.equal(returnPath('mayorista'),'/mayorista');assert.equal(returnPath('carrito'),'/carrito');for(const value of ['//evil.test','https://evil.test','/mayorista','%2f%2fevil','constructor','__proto__','toString',[],{},null])assert.equal(returnPath(value),null);});
async function fixture(t,{user=null,live=true,callbackError=false}={}){
 const calls=[];const auth={getUser:async()=>({data:{user}}),getSession:async()=>({data:{session:{access_token:'fixture.'+Buffer.from(JSON.stringify({session_id:sid})).toString('base64url')+'.signature'}}}),exchangeCodeForSession:async code=>{calls.push({code});return{error:callbackError?{}:null};},verifyOtp:async args=>{calls.push(args);return{error:callbackError?{}:null};},signUp:async args=>{calls.push(args);return{data:{session:null}};}};
 const {app}=createApp({url:'http://127.0.0.1:54321',secret:'fixture',publishable:'fixture',origin:'https://matebreak.test',shippingMode:'mock',paymentsMode:'mock',production:false},{authFactory:()=>({auth}),admin:{rpc:async(name,args)=>{calls.push({name,args});return{data:name==='mb_wholesale_access'?live:name==='mb_rol'?'cliente':[]};}}});
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>new Promise(r=>server.close(r)));
 return {calls,request:(path,method='GET',body)=>fetch('http://127.0.0.1:'+server.address().port+path,{redirect:'manual',method,headers:{origin:'https://matebreak.test','content-type':'application/json',cookie:'__Host-mb_wholesale='+'a'.repeat(64)},...(body?{body:JSON.stringify(body)}:{})})};
}
test('guest cookie never unlocks catalogue, quote, request, history or account context',async t=>{const {request,calls}=await fixture(t);for(const [path,method] of [['catalogo','GET'],['cotizar','POST'],['solicitudes','POST'],['solicitudes','GET'],['solicitudes/'+uid,'GET'],['perfil','GET']]){const r=await request('/api/mayorista/'+path,method,method==='GET'?undefined:{});assert.equal(r.status,401);assert.match(r.headers.get('cache-control'),/no-store/);}assert.equal(calls.length,0);});
test('revoked sessions and anonymous Auth identities cannot enter wholesale',async t=>{for(const options of [{user:{id:uid},live:false},{user:{id:uid,is_anonymous:true}}]){const {request,calls}=await fixture(t,options);assert.equal((await request('/api/mayorista/catalogo')).status,401);assert.ok(!calls.some(c=>c.name==='mb_wholesale_catalog'));}});
test('email callback resumes only an allowlisted destination after verification',async t=>{const {request,calls}=await fixture(t,{user:{id:uid}});assert.equal((await request('/auth/callback?code=fixture&volver=mayorista')).headers.get('location'),'/mi-cuenta?volver=mayorista&auth=confirmed');assert.equal((await request('/auth/callback?token_hash=fixture&type=email&volver=mayorista')).headers.get('location'),'/mi-cuenta?volver=mayorista&auth=confirmed');assert.ok(calls.some(c=>c.token_hash==='fixture'&&c.type==='email'));assert.equal((await request('/auth/callback?code=fixture&volver=https://evil.test')).headers.get('location'),'/mi-cuenta?auth=confirmed');assert.equal((await request('/auth/callback?token_hash=fixture&type=recovery&volver=mayorista')).headers.get('location'),'/mi-cuenta?volver=mayorista&auth=error');});
test('expired or cross-device PKCE callback preserves wholesale intent for login',async t=>{const {request}=await fixture(t,{callbackError:true});assert.equal((await request('/auth/callback?code=expired&volver=mayorista')).headers.get('location'),'/mi-cuenta?volver=mayorista&auth=error');});
test('registration sends safe email return destination with HttpOnly intent cookie',async t=>{const {request,calls}=await fixture(t);const r=await request('/api/auth/registro','POST',{email:'fixture@example.invalid',password:'local-password-only',nombre:'Cliente',apellido:'Local',whatsapp:'+54 011 12345678',provincia:'Buenos Aires',localidad:'Tandil',empresa:'Fixture',volver:'mayorista',user_id:uid});assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly/);assert.equal(calls[0].options.emailRedirectTo,'https://matebreak.test/auth/callback?volver=mayorista');assert.deepEqual(calls[0].options.data,{nombre:'Cliente Local',mayorista:{nombre:'Cliente Local',whatsapp:'+54 011 12345678',provincia:'Buenos Aires',localidad:'Tandil',empresa:'Fixture'}});});
